### PR TITLE
PCHR-2719: Disable debug mode

### PR DESCRIPTION
**Pull request by reneolivo**
## Overview
Disables debug mode from this extension by only providing minified files, and adds source maps to the build process.

This PR is part of https://github.com/civicrm/civihr/pull/2202

## Technical Details
* These were added to the build file for source maps generation:
```js
generateSourceMaps: true,
useSourceUrl: true,
```
* source maps are ignored from being commited.
* only the `js/dist/tasks-assignments.min.js` is provided

## Comments
There are no tests to run.

### CODE REVIEW

**Comment by deb1990** [comment]
@reneolivo Looks good to me

**Comment by deb1990** [comment]
@reneolivo Dont you need to modify the build process to create map files?

**Comment by bmnepali** [comment]
@reneolivo 👍 Looks good!

**Comment by deb1990** [comment]
@reneolivo Should not theses changes should go to 1.6?

**Pull request merged**
